name: random_string
description: Simple library for generating random ascii strings.
version: 1.0.0
author: Damon Douglas <douglas.damon@gmail.com>
homepage: https://github.com/damondouglas/random_string.dart

environment:
  sdk: '>=2.1.0 <3.0.0'

dev_dependencies:
  test: ^1.6.4
